# Limits for the Pilz planner (HC10DTP)
# Lower velocities than GP4 since HC10DTP is a collaborative robot
cartesian_limits:
  max_trans_vel: 0.8
  max_trans_acc: 2.0
  max_trans_dec: -4.0
  max_rot_vel: 1.2
